### ISSUE TITLE
Update out-of-limit message to include time

### ISSUE THREAD

**Issue by jordanpadams** [NASA-AMMOS/AIT-Core#100]

**Comment by MJJoyce** [comment]
Issue moved to [NASA-AMMOS/AIT-GUI #78](https://github.com/NASA-AMMOS/AIT-GUI/issues/78) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MJJoyce** [comment]
I'm going to handle this with some other changes over in the GUI repo @jordanpadams
