### ISSUE TITLE
ait-tlm-csv warning when field not detected results in a lot of spam

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#101]
`ait-tlm-csv` currently writes a warning when a particular telemetry key cannot be located in a packet before returning `None` for the value. These log messages are horribly annoying when running over a large number of packets and can result in logs being fairly useless. We should either drop the alert or update the logger to default to a higher log level to avoid all the noise.

https://github.com/NASA-AMMOS/AIT-Core/blob/master/ait/core/bin/ait_tlm_csv.py#L162

**Comment by aywaldron** [comment]
@MJJoyce As far as I can tell there are 4 options:
1. Increase `ait_tlm_csv` log level from 'warning' to 'error' (there are no other message with level 'warning' in `ait_tlm_csv.py` that would be left out)
2. Increase the default log level from 'warning' to 'error' (this will affect messages of level 'warning' in other logs)
2. Decrease this message's level from 'warning' to 'info' (or 'debug')
3. Get rid of this message completely 
Let me know which you'd prefer!

**Comment by MJJoyce** [comment]
Hanlded in #108
