### ISSUE TITLE
Stream handler calls should handle None return from handlers

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#159]
It's feasible that a handler will get input data that it can't process. With the Handler implementation this means we need to return `None` or something similar. Having the stream check for `None` and break the handler chain makes the most sense to me.

Current stream `process()`
https://github.com/NASA-AMMOS/AIT-Core/blob/master/ait/core/server/stream.py#L64
```
for handler in self.handlers:
    output = handler.handle(input_data)
    input_data = output

 self.publish(input_data)
```

Updating to something like the below would cover this situation
```
for handler in self.handlers:
    output = handler.handle(input_data)

    if output:
        input_data = output
    else:
        return

 self.publish(input_data)
```

**Comment by MJJoyce** [comment]
@aywaldron thoughts on the above?

**Comment by aywaldron** [comment]
I think this would work but we should add a log message to indicate that a failure occurred during handling of the data so that its not just lost in the void.

**Comment by seanlu99** [comment]
I'll add a log message

**Comment by seanlu99** [comment]
I didn't log the data that the CCSDSPacketHandler failed on because it doesn't display correctly in the log since it is packed binary data. Instead I just logged specific error messages in `handler.py`.
