### ISSUE TITLE
'ait-gui' plugin Test 

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#241]
Assignment: 
> Test all GUI endpoints
> - Exercise the GUI functionality and ensure the backend endpoints are functioning as expected
> - Run a sequence.  Load, run, stop and abort a script.  Send a command.  Run a search for a mnemonic. Etc

This issue captures tests on the ait-server and ait-gui plugin.  Initial testing discovered issues related to the server, so this issue is being placed in AIT-Core instead of AIT-GUI.

**Comment by nttoole** [comment]
Testing notes: 

**0. Setup**

A) Download AIT-Core. AIT-GUI, create Python3 virtual env
B) Update the standard AIT_CONFIG file to include the ait-gui plugin using default options
C) Run the ait-server

`AIT-Core/ait/core/bin/ait_server.py`

D) Open browser pointing to _localhost:8080_

E) Initiate simulated telemetry data generator

`AIT-Core/ait/core/bin/ait_server.py`

============

**I. GUI Main Panel**

![5FFDCE51-6B69-4690-83FC-C841C14A6124](https://user-images.githubusercontent.com/22964401/74964968-3327ce00-53c9-11ea-8e0f-3ab5a89a9d71.jpeg)

A) Telemetry from ait_tlm_simulate displayed in graph, 
B) Graph updates as new telemetry comes in
C) Time slider at bottom adjusts graph to subset 
D) Voltage_A correctly indicated as error value based on config in limits.yaml

============

**II.  South Panel**

A) Logs 
1) Log console appears to be working, displaying log messages regularly.
2) ISSUE - Each message appears to be appended with ‘\x00’
This seems to be originating in the server end (based on looking at the /messages endpoint).


B) Commanding
1) Send Command: typing in field displays potential matches, if no match then no suggestion.
Selecting NO_OP, hitting Ctrl+Enter works by sending command (verified in Command History tab )
2) Search: display command categories ‘CMD’,’CORE’- selecting  a category displays command instances. 
Select ‘SEQ_ENABLE_DISABLE’, panel on right shows argument fields.  
a) Filling out args goes through some validation (via the rest interface).  
b) However, sometimes sending via the associated ‘Send Command’ (when green), the command does not appear in Command History tab.  
c) Sometimes Send Command button does work, in which case right panel resets, otherwise the args panel remains, even with Send Command green.  
d) Maybe user has to click through each argument component for the Command to be sent - even tho the button is green?? 
e) Selecting SEND_STR_ARG, arg is only valid when string with no whitespace, even if adding quotes. Maybe that’s ok for AIT use cases.
f) SEND_STR_ARG throws an error in the server when trying to decode the string argument, UNLESS the fix in the primate dtype.encode() fix is in place.
g) Tested ‘CORE_SET_OP_MODE’ with enum values {SCIENCE, SAFE, SCIENCEISREAL (last one did not pass validation)}


C) Command History
1) Successfully displays the commands that have been sent.

D) Sequences
1) Selected example_sequence.txt which contains:
```
10.5 NO_OP
10 NO_OP
```
2) Clicked Send
3) Examined log panel to see commands listed
4) Question/Concern, are the preceding numbers second offset?  Where is the wait occuring?  The log timestamps indicate somewhere downstream.


E) Script Control
1) Loaded the example_script.py, which is a simple example of using Instrument API to send a NO_OP cmd.
2) Test load/run/abort
a) Created longer running script ‘sned_and_wait_script.py’ containing:

```
#!/usr/bin/env python
from ait.core import log
from ait.core.api import Instrument, wait
pref = "SendAndWaitScript: "
timeout = 5
cmdstem = 'NO_OP'
inst = Instrument()
for x in range(0, 5):
    print(pref+"Sending command...")
    inst.cmd.send(cmdstem)
    log.info(pref+" Sleeping "+str(timeout)+" seconds...")
    wait(timeout)
log.info(pref+"Script done")
```


b) Reran ait server
c) In front end, selected ‘send-wait’ script for loading
d) Ran the script, saw log  messages being printed
e) Aborted the script on the front end, witnessed log message indicating abort

Status: _send_and_wait_script.py_ execution aborted


F) Playback
Requires database setup, which Kayo is testing, so did not test feature.

**Comment by nttoole** [comment]
Python3 Issues:
1) string arguments are not being decoded correctly (dtype.py)
2) log message contents always appended with 'x\00'

Other:
1) Command tab: entering command arguments per field has inconsistent results when hitting the green 'Send Command' button

**Comment by MJJoyce** [comment]
@nttoole,

Can you open a ticket so we can follow up on `log message contents always appended with 'x\00'`

It looks like #236 was addressed in the testing PR correct?

Regarding the command tab issue, are you referring to when you click send but you need to click it twice? Or were you experiencing a different behavior?

**Comment by nttoole** [comment]
1) Created new issue #266 for the log message issue,
2) Yes, #236 should have been resolved by my testing fixes.
3) Will need to take another look.

**Comment by MJJoyce** [comment]
@nttoole, sounds good. If the command stuff is something other than the above please open another ticket. I think given the fairly benign effect of the log message issue that we can close this and track any changes over there. If you feel strongly otherwise feel free to reopen.
