### ISSUE TITLE
'openmct' plugin Test 

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#242]
This issue will track the testing and resulting issues related to Python3 and the OpenMCT plugin

**Comment by nttoole** [comment]
Testing notes:

**Early Issues while testing:**

1) While using Python 3.8, found that the gevent lib needs to be updated to 1.5a2 or later.  AIT will be advertised to work with Python 3.6/3.7.

2) Latest OpenMCT appears to break the tutorial and thus our instructions for integrating AIT.
Work around is to check out an earlier version of openmct.  We checked out the following git hash:  3dee6db5e227775ac41ef2f

**Testing:**

Setup:

1) Create top level directory, $TOP_DIR, with Python 3 virtualenv env

2) Checkout and install OpenMCT (an older version that works with tutorial)
```
cd $TOP_DIR
git clone https://github.com/nasa/openmct.git
cd openmct
git checkout 3dee6db5e227775ac41ef2f
```


3) Checkout and install AIT-Core
```
cd $TOP_DIR
git clone https://github.com/NASA-AMMOS/AIT-Core.git
```

4) Setup components by following steps in: [https://ait-core.readthedocs.io/en/latest/plugin_openmct.html](https://ait-core.readthedocs.io/en/latest/plugin_openmct.html)
a) installed http.js from OpenMct Tutorial git repo
b) update AIT config yaml to include OpenMCT plugin
c) In plugin section, include ‘debug’ field in the plugin def, setting value to ‘true’  (This will allow us to simulate telemetry)
d) update the OpenMCT _index.html_ to include http,ait-integration JS and activate the AIT config services in openmct

5) Ensure all dependencies are up to date:
a) _ait_:  pip install .
b) _openmct_: npm install

6) Run the services in separate windows (assuming proper env setup each)
a) _ait_: $TOP_DIR/AIT-Core/ait/core/bin/ait_server.py  
b) _openmct_: npm start

7) Open browser, visit OpenMCT at _localhost:8080_
Expand 1553_HS_Packet:Current_A in AIT Telemetry folder

8) In another browser window, create simulated TLM via accessing this URL multiple times:
_http://localhost:8082/tlm/debug/sim/1553_HS_Packet_

9) OpenMCT preview graph widget should indicate values for each of the debug-sim invocations. (there is an issue with the non-preview rendering the graph, sigh)


![m0DmnlzGQWeC37yZwoxJpg_thumb_4](https://user-images.githubusercontent.com/22964401/74966186-75eaa580-53cb-11ea-8c65-4e1fce10a29b.jpg)

**Comment by nttoole** [comment]
Python3 Issues:
None

**Comment by nttoole** [comment]
Other issues:
1) Make OpenMCT plugin consistent with latest OpenMCT version
2) Update our gevent when upgrading to Python 3.8

**Comment by MJJoyce** [comment]
@nttoole,

Can you update the docs with information on what version of OpenMCT needs to be used for compatibility? We can close this out after that I think

**Comment by nttoole** [comment]
@MJJoyce Can I update the docs as part of this issue or should I create a new one?

**Comment by MJJoyce** [comment]
@nttoole, this ticket is fine with me
