### ISSUE TITLE
Server is emitting log messages with ‘\x00’ appended

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#266]
While verifying components of the AIT-GUI as part of the Python3 Testing phase (#241), we discovered log messages were appearing with '\x00' appended to the end of the message.  Using browser Developer tools, it _appears_ the log messages with extra bits are being emitted by the server, so we should investigate where and resolve it.

**Comment by MJJoyce** [comment]
Moving this out of the 3.x testing to make tracking pre-release todos simpler. I don't think this needs to hold up a release.

**Comment by MJJoyce** [comment]
This actually was resolved with the changes to the server message passing formats in #299
