### ISSUE TITLE
Update CSV File Open() Parameter

### ISSUE THREAD

**Issue by Futabay** [NASA-AMMOS/AIT-Core#267]
Python3 related issue: need to replace the 'wb' mode to 'w'  ([ait_tlm_csv.py#L121](https://github.com/NASA-AMMOS/AIT-Core/blob/66f2ee05357056b0d4455129e1dc28c264d39634/ait/core/bin/ait_tlm_csv.py#L121))

**Comment by MJJoyce** [comment]
This was done in 708548490c117e3085c1b95fdf441af423ff01b1
