### ISSUE TITLE
OpenMCT plugin does not support array types in telemetry

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#289]
While updating their software to use AIT2 and the OpenMCT plugin, the AIT-MAIA reported errors while initializing the OpenMCT plugin:

```
2020-08-11T13:27:58.398 | INFO     | Running AIT OpenMCT Plugin
2020-08-11T13:27:58.401 | ERROR    | <class 'ValueError'> creating plugin 1: invalid literal for int() with base 10: '3]'
```
This appears to be happening when the plugin takes an AIT tlm dict and translates it to associated OpenMCT formatted tlm dict.  Well apparently this conversion process does not handle array types, which MAIA is using:

`MSB_U16[3]`

So please update the OpenMCT plugin to account for array types in telemetry.

**Comment by nttoole** [comment]
Small update: MAIA has since been refactoring its telemetry dictionary to remove all of the array types.
Historically, array types were barely supported in an earlier version of AIT/BLISS, but at this point, we should consider such support deprecated.

**Comment by mudinthewater** [comment]
@nttoole MCT doesn't carry a concept of an 'array', instead the individual components of it should be sent as channels. Ie 

testarraychannel [0,1,2]

would need to be: 

testarraychannel1: 0
testarraychannel2: 1
testarraychannel3: 2

Support for array channels would need to be requested over at the OpenMCT github.

**Comment by nttoole** [comment]
Since OpenMCT officially does not support array types, and MAIA has since refactored its telemetry, we will mark this as wontfix
