### ISSUE TITLE
Inaccurate log message in db.query call

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#353]
The log message in `db.InfluxDBBackend.query` is incorrectly referencing the wrong function.

https://github.com/NASA-AMMOS/AIT-Core/blob/master/ait/core/db.py#L487

Same error shows up in `db.SQLiteBackend.query` as well

https://github.com/NASA-AMMOS/AIT-Core/blob/master/ait/core/db.py#L820

**Comment by bkseto** [comment]
@mjjoyce The permalinks to the log messages look like they are outdated. Are you referring to the "query_time_range" in the log message on these lines?
- https://github.com/NASA-AMMOS/AIT-Core/blob/48006cba87b0230dee7dc91db8cc4ad8ca4d73c7/ait/core/db.py#L398
- https://github.com/NASA-AMMOS/AIT-Core/blob/48006cba87b0230dee7dc91db8cc4ad8ca4d73c7/ait/core/db.py#L470
- https://github.com/NASA-AMMOS/AIT-Core/blob/48006cba87b0230dee7dc91db8cc4ad8ca4d73c7/ait/core/db.py#L751
- https://github.com/NASA-AMMOS/AIT-Core/blob/48006cba87b0230dee7dc91db8cc4ad8ca4d73c7/ait/core/db.py#L832

**Comment by nttoole** [comment]
@bkseto based on [this version (where lines match)](https://github.com/NASA-AMMOS/AIT-Core/blob/39ecd2ad3ad1f4a72f4404e2460a9b43698d2ed3/ait/core/db.py), the answer to your question is 'yes!'.  ;)
