### ISSUE TITLE
MCT Serve limits to one connected client <cubesat issue>

### ISSUE THREAD

**Issue by mudinthewater** [NASA-AMMOS/AIT-Core#358]
MCT Server adaptation is currently limited to one connected client (serve is a while connected loop). This should be handled with threads and callbacks to manage a dictionary of connected clients.

**Comment by nttoole** [comment]
After refactoring much of the MCT Plugin to support multiple sessions, ran two instances of OpenMCT (on unique ports) which both connect to the same AIT server:

Port 8080:
![image](https://user-images.githubusercontent.com/22964401/158911335-945ab4aa-cfc9-4cc0-8a56-5931f0c35c2f.png)

Port 8088:
![image](https://user-images.githubusercontent.com/22964401/158911375-77c3d06f-56c4-4250-8692-132b4cac4c6e.png)
