### ISSUE TITLE
Test AIT with Python 3.8

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#363]
AIT currently is marked to support Python 3.7
There is some anecdotal evidence that it will also run for Python 3.8

Checkout the Core,GUI,DSN repos and run tests using Py3.8

Note: There was an [earlier issues](https://github.com/NASA-AMMOS/AIT-Core/issues/233) using gevent with Py3.8 that we marked as 'wont-fix' at the time.
The underlying issue should be resolved by now tho, but keep an eye on components that use gevent in testing.

**Comment by MJJoyce** [comment]
FYI since I've been a slacker and not opened a ticket, I'm working on redoing our packaging and testing stuff in Core. Part of that includes running the test suite across 3.7/8/9. So some of the effort here will be covered by that.

I'd also suggest we plan on support any currently maintained Python version, including dropping support when they EoL a version. Given the timing, not really worth it to do any testing against 3.6 though.

**Comment by davidryanshay** [comment]
I'm installing AIT-Core in a new virtualenv and after I checkout and run "$ pip install ." I get the error message:

> ERROR: Package 'ait-core' requires a different Python: 3.8.10 not in '<3.8,>=3.7'

@MJJoyce or @nttoole, is there a way around this?

**Comment by nttoole** [comment]
@davidryanshay Please give the following install command a whirl (we are moving towards Poetry tools for our projects):
`poetry install`

**Comment by nttoole** [comment]
Argh, there seems to be a missing import on one of the new changes.  One moment

**Comment by drshay** [comment]
Okay, I ran the install before I saw your message. I'm not very familiar with poetry, can I just run `poetry install` again once the new checkout is ready?

**Comment by nttoole** [comment]
Ok, fix to the issue is in.
I believe if you pull in the new master, then calling 'poetry install' again should do it.
That sound right to you @jasonmlkang ?

**Comment by jasonmlkang** [comment]
@nttoole I tried with python version 3.8.12 and it stalls at installing `gevent` (see screenshot below). Tried with python version 3.7 and it works with no issues. The stalling is consistent for python version 3.8.12.

![image](https://user-images.githubusercontent.com/3778622/156864829-d0f92700-9076-47e9-8d00-6a9fc3ef37e8.png)

**Comment by jasonmlkang** [comment]
@nttoole works for me!

**Comment by MJJoyce** [comment]
Going to close this since we have 3.8 testing with the new tox updates. GUI / DSN testing will be covered by tickets specific to those repos.
