### ISSUE TITLE
Raw Telemetry Decoding

### ISSUE THREAD

**Issue by ThomasWerneJPL** [NASA-AMMOS/AIT-Core#382]
# Error

Running `ait-tlm-csv` with a `--fields` argument gives the following error:

```
Traceback (most recent call last):
  File "<redacted>/ait-tlm-csv", line 8, in <module>
    sys.exit(main())
  File "<redacted>/ait_tlm_csv.py", line 94, in main
    raw = fldname.split('.')
TypeError: a bytes-like object is required, not 'str'
```

# Diagnosis
The problem line is:

https://github.com/NASA-AMMOS/AIT-Core/blob/40abda33b2a32a49eeb4d00d373f3b49aa1e7981/ait/core/bin/ait_tlm_csv.py#L94-L96

# Correction
Fix is: `s/rb/r/`

# Environment info
Python: 3.7.11
ait-core version: 2.3.5
OS: Ubuntu 20.04.1

**Comment by MJJoyce** [comment]
Fixed in #386
