### ISSUE TITLE
Exception message when opcode does not fit unsigned int is unhelpful

### ISSUE THREAD

**Issue by Mejiro-McQueen** [NASA-AMMOS/AIT-Core#395]
The default error message is not descriptive enough for the user to quickly find their error.
Need concise and useful failures logs for smoke testing dictionaries.

**Comment by Mejiro-McQueen** [comment]
#397

**Comment by nttoole** [comment]
Fixed by https://github.com/NASA-AMMOS/AIT-Core/pull/397
