### ISSUE TITLE
Yaml `!include` is broken

### ISSUE THREAD

**Issue by jasonmlkang** [NASA-AMMOS/AIT-Core#405]
**Scenario**
```
import ait.core
import ait.core.cmd as cmd

ait.config.get('cmddict.filename', None) #=> .../config/cmd.yaml

cmd.getDefaultDict() #=> yaml.constructor.ConstructorError: could not determine a constructor for the tag '!Command'
```

**Comment by MJJoyce** [comment]
What's the context here? Need example command dictionary files demonstrating the issue you're running into / reporting. Or did we regress somehow?

**Comment by jasonmlkang** [comment]
@MJJoyce I think we regress somehow. To replicate this issue, checkout out ait-core master, and run cmd pytest `pytest ./tests/ait/core/test_cmd.py -k 'testGetDefaultDict'`.

**Comment by jasonmlkang** [comment]
This issue is caused by outdated library on my local python env.
