### ISSUE TITLE
Derived channels and EU channels should be treated identically to natural channels and be included with packet streams

### ISSUE THREAD

**Issue by mudinthewater** [NASA-AMMOS/AIT-Core#411]
When an EU or derived channel is generated, its associated metadata should be included with the source packet as though it was a channel in that packet, so that display tools such as MCT or AIT-GUI have access to it.

**Comment by MJJoyce** [comment]
Packet definitions already track what is necessary for raw to EU conversion and derived channels. From a API-user perspective they're not really differentiable from a "normal" raw field in the packet. How plugins or external tools are fed packet data is entirely within the purvue of the plugin implementation. But, once something in the pipeline has a Packet object it has everything it needs to know.

Not seeing the value (or even the point) of a change here. If you have some additional thoughts feel free to throw them on here.
