### ISSUE TITLE
Telemetry streams should be decoded only once, then passed decoded to outputs. 

### ISSUE THREAD

**Issue by mudinthewater** [NASA-AMMOS/AIT-Core#412]
The "decode_message" method should only be called once. After the telemetry message is decoded, the resulting values should be passed to interfaces, not re-decoded. This allows a single-source of decom. Having multiple sources is both inefficient and introduces an extra avenue for faults.

**Comment by MJJoyce** [comment]
The `decode_message` utility is a helper function for decoding a 0MQ socket message. It should be used at any point necessary in the server architecture where messages are being sent over 0MQ. It shows up precisely two times in the Core codebase. There's plenty of bad things to say about `decode_message` (like its abhorrent `Exception` catch), but this ain't it.
