### ISSUE TITLE
Drop documentation upgrade scripts now that ReadTheDocs builds are up

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#43]
- [ ] Drop ait-core/build/update_docs_release.sh
- [ ] Drop ait-gui/build/update_docs_release.sh
- [ ] Drop ait-dsn/build/update_docs_release.sh

**Comment by lorsposto** [comment]
Related issues: nasa-ammos/ait-gui#37, nasa-ammos/ait-dsn#29
