### ISSUE TITLE
AIT Core Telemetry Data, How to? Help required

### ISSUE THREAD

**Issue by nchanilk** [NASA-AMMOS/AIT-Core#431]
Hi Team,
I'm new to AIT Core and GUI. I did set up the virtual environment and ran the ait-server. I've a few questions, any help would be appreciated.
1. How do I send the telemetry data from ait-server? Are we having the sample data included? How to give the data location to load?
2. What's the data format I've to give?
3. I'm getting the "Config parameter dsn.cfdp.mib.path specifies nonexistent" for all the paths, how to resolve them?
Right now I get blank UI for AIT GUI, Any help would be appreciated.

Thanks,
Anil

**Comment by MJJoyce** [comment]
Hey @nchanilk,

> How do I send the telemetry data from ait-server? Are we having the sample data included? How to give the data location to load?

Assuming you're running the default dictionaries and example configuration, you can throw example data at the server with `ait-example`. That sending a packet of marching integer values to the server.
https://github.com/NASA-AMMOS/AIT-GUI/blob/master/ait/gui/bin/ait_example.py

> What's the data format I've to give?
That ultimately depends on how you've configured stuff. Check out the `ait-example` script above for an example.

> I'm getting the "Config parameter dsn.cfdp.mib.path specifies nonexistent" for all the paths, how to resolve them?
The default configuration includes paths that don't necessarily exist on any given system. We use them for development, etc. You can delete them from your configuration or ignore the warnings.

> Right now I get blank UI for AIT GUI, Any help would be appreciated.
Can you elaborate on what you have setup and installed? If you've installed Core and GUI and added the relevant config from the GUI documentation you shouldn't be seeing a blank page.


I'm going to close this ticket out. If you have follow up questions please send an email to our mailing list. The [Join the Community section of the wiki](https://github.com/NASA-AMMOS/AIT-Core/wiki#join-the-community) has a link to get you there.

**Comment by nchanilk** [comment]
thanks, @MJJoyce for all your guidance and help. It's possible that I've running python 3.8 and may need to downgrade to 3.7 to make it work for some of the components, I'll work on it and open a new ticket if required.
Again, thanks a lot for your help.
