### ISSUE TITLE
Update deprecated method call in dmc.py

### ISSUE THREAD

**Issue by jordanpadams** [NASA-AMMOS/AIT-Core#51]
This is a fun one.

https://github.com/NASA-AMMOS/AIT-Core/blob/master/bliss/core/dmc.py#L124 is where we throw the deprecation WARNING message for the new GPS Leap Seconds method, but then 9 lines above it we call that deprecated method :-) (https://github.com/NASA-AMMOS/AIT-Core/blob/master/bliss/core/dmc.py#L115)

**Comment by MJJoyce** [comment]
Handled in #54
