### ISSUE TITLE
Ensure ait-pcap.py outputs a PCAP Global Header

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#78]
Update `ait-pcap.py` so that a PCAP Global Header is added to the resulting file to ensure validity. The tools don't seem to care that this is missing but we should make sure we're outputting valid PCAP files.

**Comment by MJJoyce** [comment]
@aywaldron, to confirm what you're getting at here. You're creating an example PCAP via `pcap.query` and seeing the PCapGlobalHeader (so we can likely say that this ticket isn't needed), correct?

**Comment by aywaldron** [comment]
@MJJoyce Yes that's correct. Here's where the example PCAP file is created, which does contain a global header: https://github.com/NASA-AMMOS/AIT-Core/blob/43058dfecb86df853c37b4893df99ae4617a31e4/ait/core/test/test_pcap.py#L303

**Comment by MJJoyce** [comment]
+1, thanks @aywaldron. I'll close this then. Thanks for investigating!
